version: 1
builder:
  configs:
    - documentation_targets:
        - Voxelia
        - VoxeliaSpatial
        - VoxeliaCore
        - VoxeliaStorage
        - VoxeliaExecution
        - VoxeliaImaging
        - VoxeliaGeometry
        - VoxeliaRendering
        - VoxeliaInteraction
        - VoxeliaCPU
        - VoxeliaMetal
        - VoxeliaValidation
