// SPDX-License-Identifier: MIT

import Foundation
import Testing

@testable import VoxeliaCore

@Suite("MetadataBinary")
struct MetadataBinaryTests {
    @Test("[Unit][CDMS-72][VOX-META-002] snapshots defeat no-copy backing mutation")
    func snapshotsDefeatNoCopyMutation() {
        let capacity = 4
        let backing = UnsafeMutableRawPointer.allocate(
            byteCount: capacity,
            alignment: 1
        )
        defer { backing.deallocate() }
        backing.copyMemory(from: [1, 2, 3, 4] as [UInt8], byteCount: capacity)

        let noCopyData = Data(
            bytesNoCopy: backing,
            count: capacity,
            deallocator: .none
        )
        let value = MetadataBinary(bytes: noCopyData)
        var members: Set<MetadataBinary> = [value]

        backing.copyMemory(from: [9, 9, 9, 9] as [UInt8], byteCount: capacity)

        #expect(Array(value.bytes) == [1, 2, 3, 4])
        #expect(members.contains(value))
        #expect(members.remove(value) != nil)
    }

    @Test("[Unit][VOX-META-002] snapshots are independent of ordinary sources")
    func snapshotsAreIndependent() {
        var mutableData = Data([1, 2])
        let fromData = MetadataBinary(bytes: mutableData)
        mutableData.append(3)
        #expect(Array(fromData.bytes) == [1, 2])

        var mutableArray: ContiguousArray<UInt8> = [7, 8]
        let fromArray = MetadataBinary(bytes: mutableArray)
        mutableArray.append(9)
        #expect(Array(fromArray.bytes) == [7, 8])
    }

    @Test("[Unit][VOX-API-003] identity is exact count and ordered bytes")
    func identityIsExactBytes() {
        let empty = MetadataBinary(bytes: [UInt8]())
        #expect(empty.bytes.isEmpty)
        #expect(empty != MetadataBinary(bytes: [0]))

        #expect(
            MetadataBinary(bytes: [1, 2]) != MetadataBinary(bytes: [2, 1])
        )
        #expect(
            MetadataBinary(bytes: [1, 2]) != MetadataBinary(bytes: [1, 2, 0])
        )
        #expect(
            Set([
                MetadataBinary(bytes: [1, 2]),
                MetadataBinary(bytes: [1, 2]),
                MetadataBinary(bytes: [2, 1]),
            ]).count == 2
        )

        let allValues = MetadataBinary(bytes: Array(UInt8.min...UInt8.max))
        #expect(allValues.bytes.count == 256)
        #expect(allValues.bytes[128] == 128)

        requireSendable(MetadataBinary.self)
    }

    @Test("[Unit][VOX-API-004] Codable matches the RFC 4648 canonical vectors")
    func codableMatchesCanonicalVectors() throws {
        let vectors: [(bytes: [UInt8], encoded: String)] = [
            ([], ""),
            (Array("f".utf8), "Zg=="),
            (Array("fo".utf8), "Zm8="),
            (Array("foo".utf8), "Zm9v"),
            (Array("foob".utf8), "Zm9vYg=="),
            (Array("fooba".utf8), "Zm9vYmE="),
            (Array("foobar".utf8), "Zm9vYmFy"),
            ([0xFB, 0xFF], "+/8="),
            ([0xFF, 0xEF, 0xBE], "/+++"),
        ]
        for vector in vectors {
            let value = MetadataBinary(bytes: vector.bytes)
            #expect(MetadataBinary.encodeCanonicalBase64(value.bytes) == vector.encoded)

            let data = try JSONEncoder().encode([value])
            let object = try #require(
                JSONSerialization.jsonObject(with: data) as? [String]
            )
            #expect(object == [vector.encoded])
            #expect(try JSONDecoder().decode([MetadataBinary].self, from: data) == [value])
        }
    }

    @Test("[Unit][VOX-API-004] generated byte arrays round trip bit-exactly")
    func generatedArraysRoundTrip() throws {
        var state: UInt64 = 0x9E3779B97F4A7C15
        func nextByte() -> UInt8 {
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            return UInt8(truncatingIfNeeded: state >> 33)
        }

        for length in 0...96 {
            let bytes = (0..<length).map { _ in nextByte() }
            let value = MetadataBinary(bytes: bytes)
            let encoded = MetadataBinary.encodeCanonicalBase64(value.bytes)
            #expect(encoded.utf8.count == MetadataBinary.encodedUTF8Count(byteCount: length))
            let decoded = MetadataBinary.decodeCanonicalBase64(Array(encoded.utf8))
            #expect(decoded.map(Array.init) == bytes)
        }
    }

    @Test("[Unit][VOX-ERR-001] rejects every noncanonical semantic string")
    func rejectsNoncanonicalStrings() {
        let invalidStrings = [
            "Zg",
            "Zg=",
            "Zg===",
            "Zh==",
            "Zm9=",
            "====",
            "=g==",
            "Z===",
            "AB=C",
            "Zg==Zg==",
            "Zg == ",
            " Zm9v",
            "Zm9v\n",
            "Zm9v\r\n",
            "-_8=",
            "Zé==",
            "Zg\u{3D}\u{FF00}",
        ]
        for invalidString in invalidStrings {
            #expect(
                MetadataBinary.decodeCanonicalBase64(Array(invalidString.utf8)) == nil,
                "Expected rejection: \(invalidString)"
            )
        }

        // "Zg==Zg==" style embedded padding must fail through the full
        // decoder as well, with one value-redacted failure.
        for invalidJSON in [#""Zg""#, #""Zh==""#, #""-_8=""#] {
            do {
                _ = try JSONDecoder().decode(
                    MetadataBinary.self,
                    from: Data(invalidJSON.utf8)
                )
                #expect(Bool(false), "Expected a noncanonical string to fail decoding.")
            } catch DecodingError.dataCorrupted(let context) {
                #expect(context.codingPath.isEmpty)
                #expect(context.underlyingError == nil)
                #expect(!context.debugDescription.contains("Z"))
            } catch {
                #expect(Bool(false), "Expected dataCorrupted, received \(error).")
            }
        }
    }

    @Test("[Unit][VOX-API-004][VOX-ERR-001] decoding rejects wrong shapes independently")
    func decodingRejectsWrongShapes() throws {
        do {
            _ = try JSONDecoder().decode(MetadataBinary.self, from: Data("null".utf8))
            #expect(Bool(false), "Expected null to fail decoding.")
        } catch DecodingError.valueNotFound {
            // Null is rejected for the non-optional string.
        } catch {
            #expect(Bool(false), "Expected valueNotFound, received \(error).")
        }

        for wrongShape in ["1", "true", "[]", "{}"] {
            do {
                _ = try JSONDecoder().decode(
                    MetadataBinary.self,
                    from: Data(wrongShape.utf8)
                )
                #expect(Bool(false), "Expected a wrong-shaped value to fail decoding.")
            } catch DecodingError.typeMismatch {
                // Non-string shapes are rejected before Base64 validation.
            } catch {
                #expect(Bool(false), "Expected typeMismatch, received \(error).")
            }
        }

        // The wrapper never consults Foundation data strategies.
        let value = MetadataBinary(bytes: [0xFB, 0xFF])
        let payload = try JSONEncoder().encode([value])
        for strategy in [
            JSONDecoder.DataDecodingStrategy.base64,
            .deferredToData,
        ] {
            let configured = JSONDecoder()
            configured.dataDecodingStrategy = strategy
            #expect(
                try configured.decode([MetadataBinary].self, from: payload) == [value]
            )
        }
    }

    @Test("[Unit][VOX-SEC-001] count preflight is overflow-safe without allocation")
    func countPreflightIsOverflowSafe() {
        #expect(MetadataBinary.encodedUTF8Count(byteCount: 0) == 0)
        #expect(MetadataBinary.encodedUTF8Count(byteCount: 1) == 4)
        #expect(MetadataBinary.encodedUTF8Count(byteCount: 3) == 4)
        #expect(MetadataBinary.encodedUTF8Count(byteCount: 4) == 8)
        #expect(MetadataBinary.encodedUTF8Count(byteCount: Int.max) == nil)
        #expect(MetadataBinary.encodedUTF8Count(byteCount: -1) == nil)

        #expect(
            MetadataBinary.decodedByteCount(encodedUTF8Count: 0, paddingCount: 0) == 0
        )
        #expect(
            MetadataBinary.decodedByteCount(encodedUTF8Count: 4, paddingCount: 2) == 1
        )
        #expect(
            MetadataBinary.decodedByteCount(encodedUTF8Count: 4, paddingCount: 1) == 2
        )
        #expect(
            MetadataBinary.decodedByteCount(encodedUTF8Count: 4, paddingCount: 0) == 3
        )
        #expect(
            MetadataBinary.decodedByteCount(encodedUTF8Count: 6, paddingCount: 0) == nil
        )
        // A near-Int.max encoded count preflights its exact decoded count
        // through checked arithmetic with no corresponding allocation.
        #expect(
            MetadataBinary.decodedByteCount(
                encodedUTF8Count: Int.max - 3,
                paddingCount: 0
            ) == (Int.max - 3) / 4 * 3
        )
        #expect(
            MetadataBinary.decodedByteCount(encodedUTF8Count: -4, paddingCount: 0) == nil
        )
        #expect(
            MetadataBinary.decodedByteCount(encodedUTF8Count: 0, paddingCount: 2) == nil
        )
    }

    @Test("[Unit][VOX-SEC-001] deterministic codec fuzzing is total and canonical")
    func codecFuzzingIsTotalAndCanonical() {
        var state: UInt64 = 0x853C49E6748FEA9B
        func nextByte() -> UInt8 {
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            return UInt8((state >> 33) % 96) + 32
        }

        var accepted = 0
        for length in 0...24 {
            for _ in 0..<96 {
                let candidate = (0..<length).map { _ in nextByte() }
                guard let decoded = MetadataBinary.decodeCanonicalBase64(candidate)
                else { continue }
                accepted += 1
                // The profile is canonical: an accepted string is exactly
                // the re-encoding of its decoded bytes.
                #expect(
                    Array(MetadataBinary.encodeCanonicalBase64(decoded).utf8)
                        == candidate
                )
            }
        }
        // The empty string is always accepted; random acceptance is rare.
        #expect(accepted >= 24)
    }

    private func requireSendable<Value: Sendable>(_ type: Value.Type) {}
}
