// SPDX-License-Identifier: MIT

import VoxeliaCore
import VoxeliaStorage

/// One brick of a study-cache generation sweep: the identity to decode
/// and the caller-measured reconstruction cost the cache's eviction
/// ordering consumes.
public struct StudyCacheBrick: Sendable, Hashable {
    /// The brick to decode into the store.
    public let identity: BrickIdentity
    /// The eviction-ordering cost units for this brick's entry.
    public let reconstructionCost: UInt64

    public init(identity: BrickIdentity, reconstructionCost: UInt64) {
        self.identity = identity
        self.reconstructionCost = reconstructionCost
    }
}

/// The progress of one study-cache generation sweep after one brick.
public struct StudyCacheProgress: Sendable, Equatable {
    /// The number of bricks processed so far, including this one.
    public let completedBrickCount: Int
    /// The total number of bricks in the sweep.
    public let totalBrickCount: Int

    public init(completedBrickCount: Int, totalBrickCount: Int) {
        self.completedBrickCount = completedBrickCount
        self.totalBrickCount = totalBrickCount
    }
}

/// The study-cache generation stage per `ADR-0341`.
///
/// Sweeps a study's bricks, in caller order and one at a time, through
/// the accepted cache-through-broker entry point, so the decoded brick
/// store of `ADR-0338` decision 2 is generated by a stage with a start,
/// per-brick progress and a completion. The sweep runs inside the
/// caller's task, so the caller's chosen priority — `.utility` for
/// background generation — propagates structurally into every brick
/// computation, while interactive callers reach the same store through
/// the same broker inside their own higher-priority tasks and are never
/// queued behind the sweep. Cancellation composes the broker's
/// last-awaiter rule; a cancelled sweep stops without a completion.
public enum StudyCacheGenerator {
    /// Sweeps every brick into the store, reporting progress after each.
    ///
    /// A brick already admitted — by an interactive caller or an earlier
    /// sweep entry — is a cache hit, not a recomputation; a brick the
    /// sweep and an interactive caller race on is computed once through
    /// the broker's deduplication.
    ///
    /// - Throws: `CancellationError` when the sweep's task is cancelled,
    ///   or the audited typed errors of the broker, cache and
    ///   computation contracts, aborting the sweep fail-closed.
    public static func generate(
        bricks: [StudyCacheBrick],
        representation: ExecutionClaimToken,
        generation: UInt64,
        visible: Bool,
        cache: BrickResultCache,
        broker: BrickRequestBroker,
        progress: (@Sendable (StudyCacheProgress) -> Void)?,
        compute: @escaping @Sendable (BrickIdentity) async throws -> ContiguousArray<UInt8>
    ) async throws {
        for (index, brick) in bricks.enumerated() {
            try Task.checkCancellation()
            let identity = brick.identity
            _ = try await cache.result(
                for: identity,
                representation: representation,
                generation: generation,
                visible: visible,
                reconstructionCost: brick.reconstructionCost,
                broker: broker,
                compute: { try await compute(identity) }
            )
            progress?(
                StudyCacheProgress(
                    completedBrickCount: index + 1,
                    totalBrickCount: bricks.count
                )
            )
        }
    }
}
